[project]
name = "gap-hunter-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docling>=2.82.0",
    "graphviz>=0.21",
    "langchain-community>=0.4.1",
    "langchain-ollama>=1.0.1",
    "llama-cpp-python>=0.3.20",
    "pydantic>=2.0",
]
