"""
Pydantic schemas for the Policy Revision Agent (Phase 3).

Three-role RAPTOR + CoVe architecture:
  - AdditionBlock: output of the Addition Writer (delta only, never full section)
  - ClusterSummary: RAPTOR level-1 summary of all blocks in one NIST function group
  - VerificationQuestion: CoVe step-2 output — a single yes/no check for a block
  - IntegrationResult: output of the Integration Editor (final merged section)
  - SectionRevision: kept for new_section action only
  - RevisionValidationResult: kept for simple accept/reject responses
  - TextSummary: output of the shared LLM summarizer utility
  - SummaryValidationResult: used by the summarizer validation loop
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Kept unchanged — used for new_section action only
# ---------------------------------------------------------------------------


class SectionRevision(BaseModel):
    """LLM output for creating a brand-new policy section."""

    action: Literal["new_section"] = Field(
        description="Always 'new_section' — this schema is only used when creating new sections.",
    )
    section_title: str = Field(
        description="Title for the new section.",
    )
    revised_content: str = Field(
        description="Complete content for the new section.",
    )
    subcategory_id: str = Field(
        description="NIST subcategory ID this section addresses, e.g. 'GV.OC-03'.",
    )
    changes_summary: str = Field(
        description="1-2 sentence description of what was created.",
    )


class RevisionValidationResult(BaseModel):
    """Simple accept/reject result used in multiple validation steps."""

    is_acceptable: bool = Field(
        description="True if the content is acceptable. False if there are issues.",
    )
    issues: list[str] = Field(
        default_factory=list,
        description="Specific problems found. Empty if is_acceptable is True.",
    )


# ---------------------------------------------------------------------------
# New schemas for the RAPTOR + CoVe architecture
# ---------------------------------------------------------------------------


class AdditionBlock(BaseModel):
    """
    Output of the Addition Writer — the delta block for one gap.

    The LLM writes ONLY this new content. It never sees or reproduces
    the accumulated section. Code merges all blocks at the end.
    """

    subcategory_id: str = Field(
        description="NIST subcategory ID this block addresses, e.g. 'PR.AA-03'.",
    )
    heading: str = Field(
        description=(
            "Short subsection heading for this block, e.g. "
            "'Multi-Factor Authentication Requirements'. Used in the cluster "
            "summary so subsequent writers know what is already covered."
        ),
    )
    content: str = Field(
        description=(
            "The new policy content only. Do NOT include the original section text. "
            "Start with the heading as a markdown ### header. "
            "Use 'shall', 'must', 'will' language. Be specific and actionable."
        ),
    )
    changes_summary: str = Field(
        description="One sentence describing what requirement this block adds.",
    )


class VerificationQuestion(BaseModel):
    """
    CoVe step-2/3 schema — a single yes/no question used to verify
    that an AdditionBlock actually addresses a specific requirement.

    Generated by the Questioner, answered by the Verifier independently.
    """

    question: str = Field(
        description=(
            "A specific yes/no question that tests whether the block addresses "
            "one concrete requirement from the gap. E.g. 'Does the block "
            "explicitly mandate MFA for remote access connections?'"
        ),
    )
    answer: bool = Field(
        description="True if the block answers yes to the question, False otherwise.",
    )
    evidence: str = Field(
        description=(
            "One sentence quoting or paraphrasing the relevant text from the block "
            "that supports the answer. If answer is False, state what is missing."
        ),
    )


class ClusterSummary(BaseModel):
    """
    RAPTOR level-1 summary of all AdditionBlocks written for one NIST
    function group (e.g. all Protect gaps targeting Section 4).

    Passed to subsequent Addition Writers as compact context so they
    know what has already been added without receiving the full text.
    """

    function_name: str = Field(
        description="NIST function name, e.g. 'Protect'.",
    )
    covered_ids: list[str] = Field(
        description="List of subcategory IDs covered by the blocks in this cluster.",
    )
    summary: str = Field(
        description=(
            "2-4 sentence summary of what requirements have been added in this cluster. "
            "Mention key topics (e.g. 'MFA, account lifecycle, RBAC') so subsequent "
            "writers can avoid repeating them."
        ),
    )


class IntegrationResult(BaseModel):
    """
    Output of the Integration Editor — the final fluent merged section.

    Runs once per section after all AdditionBlocks have been collected
    and cluster summaries generated. Merges original content + all blocks
    into a single coherent policy section.
    """

    integrated_content: str = Field(
        description=(
            "The complete merged section text. Must contain: "
            "(1) the original section content intact at the top, "
            "(2) all addition blocks merged below it in a coherent flow, "
            "with repetition eliminated, consistent terminology, and "
            "appropriate transitions between subsections."
        ),
    )
    covered_subcategory_ids: list[str] = Field(
        description=(
            "List of all subcategory IDs whose requirements appear in the "
            "integrated content. Used by the validator to confirm nothing was dropped."
        ),
    )
    changes_summary: str = Field(
        description="1-2 sentences summarising what was added to the section overall.",
    )


# ---------------------------------------------------------------------------
# Shared summarizer schemas — used by text_summarizer.py across all agents
# ---------------------------------------------------------------------------


class TextSummary(BaseModel):
    """
    Output of the LLM summarizer utility.

    Carries both the compressed summary and a structured checklist of key points
    so the validator can verify completeness without re-reading the full original.

    Key constraints to prevent JSON truncation on a 2B model:
      - summary is capped at 2000 chars (enforced via schema description + prompt)
      - key_points is capped at 15 items (the model cannot reliably track more
        than 15 distinct facts in a single generation pass without losing some;
        beyond 15 the validator loop becomes a death spiral)
    """

    summary: str = Field(
        description=(
            "A dense, lossless summary of the source text. Every requirement, "
            "action item, subcategory ID, statistic, and named entity from the "
            "original must appear. Compress by removing filler prose and formatting "
            "noise — keep every concrete fact. Use bullet points. "
            "MUST be under 2000 characters."
        ),
    )
    key_points: list[str] = Field(
        description=(
            "List of the most important distinct facts or requirements from the "
            "source text. Maximum 15 items — group related specifics into one item "
            "rather than listing every sub-requirement separately. "
            "These are used by the validator to verify nothing critical was dropped."
        ),
    )
    source_char_count: int = Field(
        description="Character count of the original source text that was summarized.",
    )


class SummaryLossCheck(BaseModel):
    """
    Output of the summarizer validator — checks whether the summary is lossless.

    The validator receives the key_points list from TextSummary and the summary
    text, and verifies that every key point is represented in the summary.
    This avoids re-reading the original full text in the validation call.
    """

    is_lossless: bool = Field(
        description=(
            "True if every key point from the list appears (possibly paraphrased) "
            "in the summary. False if any key point is missing or distorted."
        ),
    )
    missing_points: list[str] = Field(
        default_factory=list,
        description=(
            "Key points that are absent or materially distorted in the summary. "
            "Empty if is_lossless is True."
        ),
    )
